# 时间序列的处理

在金融数据分析中，最经常遇到的数据就是金融时间序列

时间序列相较于普通的截面数据，有自身的一些特殊需求，如数据时间频率的转换，交易日非交易日的处理等等

pandas针对金融时间序列的特殊数据分析需求，专门开发了一系列用于时间处理的操作

但在学习这些操作之前，我们需要先了解，python是如何存储时间的。

## python的时间模块——datetime模块

在我们的数据库系统里，时间是一个很重要的组成部分，日常最方便的表示时间的方式就是8位字符串或者是8位数字

例如，2008年1月1日，可以用字符串表示为"20080101"，或用数字表示为20080101

但仅仅使用数字或字符串表示时间，仅仅具有 __区分功能__ ，而没有 __运算功能__

意思是可以通过字符串和数字的不同表示不同的时间，但是却无法进行时间的各种运算如时间偏移，频率转换

例如20080131之后一天，如果直接加1的话，得到的是20080132，不是一个合法的时间格式

然而自己写函数进行判断麻烦且没有必要，因为python通过datetime模块较好的解决了这个问题

首先我们import datetime模块

In [2]:
import datetime

使用datetime模块里的datetime类可以表示时间

In [3]:
dt = datetime.datetime(2008, 1, 1)

#### 注意是datetime模块里的datetime类，datetime.datetime才可以访问，很多初学者容易直接键入datetime

#### datetime是模块
#### datetime.datetime才是类

最简单的构造datetime的方式是通过构造函数（注意datetime.datetime的构造函数是支持输入小时和分钟，秒等的，但是我们基本上遇不到高频数据，所以在后面的分析中，我们不会接触到日频率以下的表示）

### 构建datetime对象及与时间字符串的转换

构建一个datetime对象可以通过以下几种方式：

1.直接调用datetime.datetime的构造函数

In [4]:
dt = datetime.datetime(2008, 1, 1)
dt

datetime.datetime(2008, 1, 1, 0, 0)

In [5]:
dt.year

2008

In [6]:
dt.month

1

In [7]:
dt.day

1

2.通过时间字符串格式化得到

In [8]:
dt_str = "20090101"
dt = datetime.datetime.strptime(dt_str, "%Y%m%d")
dt

datetime.datetime(2009, 1, 1, 0, 0)

%加字母用来表示时间格式  %Y表示4位数字年份，%m表示2位数字月份，%d表示2位数字的日期

%Y%m%d格式就会将前4位数字识别为年份，随后的2位数字识别为月份，再随后的2位数字识别为日期。  
如果字符串和格式不匹配就会报错

In [10]:
dt_str = "20092-01-01"
dt = datetime.datetime.strptime(dt_str, "%Y-%m-%d")
dt

ValueError: time data '20092-01-01' does not match format '%Y-%m-%d'

In [11]:
dt_str = "2009-01-31"
dt = datetime.datetime.strptime(dt_str, "%Y-%m-%d")
dt

datetime.datetime(2009, 1, 31, 0, 0)

当然除了这三个时间格式还有很多其他的时间格式

%y 两位数的年份表示（00-99） 

%Y 四位数的年份表示（0000-9999）

%m 月份（01-12）

%d 月内中的一天（00-31）

%H 24小时制小时数（00-23）

%I 12小时制小时数（01-12）

%M 分钟数（00-59）

%S 秒（00-59）

%a 本地简化星期名称 (Thu)

%A 本地完整星期名称 (Thursday)

%b 本地简化的月份名称 (Jan)

%B 本地完整的月份名称 (January)

%c 本地相应的日期表示和时间表示 (Thu Jan  1 00:00:00 2009)

%j 年内的一天（001-366）

%p 本地A.M.或P.M.的等价符

%U 一年中的星期数（00-53）星期天为星期的开始

%w 星期（0-6），星期天为星期的开始

%W 一年中的星期数（00-53）星期一为星期的开始

%x 本地相应的日期表示 (01/31/09)

%X 本地相应的时间表示 (00:00:00)

%Z 当前时区的名称

当然大多数我们都用不到

datetime.datetime.strptime方法用来将字符串转换为datetime.datetime对象       
也可以使用datetime.datetime.strftime方法将datetime.datetime对象转换成一定格式的字符串    
这种字符串与datetime.datetime对象的互相转换是非常常用的

In [12]:
dt

datetime.datetime(2009, 1, 31, 0, 0)

In [13]:
dt.strftime("%Y%m%d")

'20090131'

In [14]:
dt.strftime("%Y-%m-%d")

'2009-01-31'

In [15]:
dt.strftime("%Y-%m-%d %H:%M:%S")

'2009-01-31 00:00:00'

例如，我们有一个列表里，全是8位字符串（例如"20090101"）的时间，想转换成靠直线连接年月日的字符串（"2009-01-01"）

In [16]:
dt_str_list1 = ["20090101", "20090102", "20090103", "20090104", "20090105"]
dt_str_list2 = [datetime.datetime.strptime(dt_str, "%Y%m%d").strftime("%Y-%m-%d") for dt_str in dt_str_list1]
dt_str_list2

['2009-01-01', '2009-01-02', '2009-01-03', '2009-01-04', '2009-01-05']

### datetime对象的运算

对时间进行偏移运算，需要使用datetime.timedelta对象

In [17]:
dt

datetime.datetime(2009, 1, 31, 0, 0)

In [18]:
dt + datetime.timedelta(1)

datetime.datetime(2009, 2, 1, 0, 0)

In [19]:
dt + datetime.timedelta(5)

datetime.datetime(2009, 2, 5, 0, 0)

In [20]:
dt + datetime.timedelta(1)*2

datetime.datetime(2009, 2, 2, 0, 0)

## pandas对于时间的处理

In [21]:
import pandas as pd
import numpy as np

当将一个全为datetime.datetime对象的集合数据结构转换为pandas中的数据类型时（Index Series），pandas会自动识别，并将其转换为特定类型

例如

In [22]:
dt_list = [datetime.datetime(2008, 1, 1), datetime.datetime(2008, 1, 2), datetime.datetime(2008, 1, 3), datetime.datetime(2008, 1, 4)]

In [23]:
dt_list

[datetime.datetime(2008, 1, 1, 0, 0),
 datetime.datetime(2008, 1, 2, 0, 0),
 datetime.datetime(2008, 1, 3, 0, 0),
 datetime.datetime(2008, 1, 4, 0, 0)]

In [24]:
pd.Series(dt_list)

0   2008-01-01
1   2008-01-02
2   2008-01-03
3   2008-01-04
dtype: datetime64[ns]

注意这里的Series的dtype不是常见的int64 float64 object，而是专门用来存储时间的datetime64[ns]

In [25]:
pd.Index(dt_list)

DatetimeIndex(['2008-01-01', '2008-01-02', '2008-01-03', '2008-01-04'], dtype='datetime64[ns]', freq=None)

转换为Index则会自动识别时间并生成专用的DatetimeIndex，DatetimeIndex也是一种Index，Index有的属性和方法他都有，但是他还有Index没有的一些专门处理时间的属性和方法（实际上DatetimeIndex类是继承自Index类的，感兴趣的可以百度 python类的继承，不感兴趣可以无视）

当然有的时候是从一个全为时间字符串的集合数据结构进行转换的，pandas提供了to_datetime函数

In [26]:
dt_str_list1 = ["20090101", "20090102", "20090103", "20090104", "20090105"]
dt_str_list2 = ["2009-01-01", "2009-01-02", "2009-01-03", "2009-01-04", "2009-01-05"]
dt_str_ser1 = pd.Series(dt_str_list1)
dt_str_ser2 = pd.Series(dt_str_list2)

In [27]:
pd.to_datetime(dt_str_list1)

DatetimeIndex(['2009-01-01', '2009-01-02', '2009-01-03', '2009-01-04',
               '2009-01-05'],
              dtype='datetime64[ns]', freq=None)

In [28]:
pd.to_datetime(dt_str_list2)

DatetimeIndex(['2009-01-01', '2009-01-02', '2009-01-03', '2009-01-04',
               '2009-01-05'],
              dtype='datetime64[ns]', freq=None)

转list会自动生成DatetimeIndex（因为大多数情况下我们将时间转换成pandas里的数据结构，都是想用作Index，所以pd.to_datetime函数设计的时候就默认了生成的数据结构）

In [29]:
当然转Series就是

NameError: name '当然转Series就是' is not defined

In [30]:
pd.to_datetime(dt_str_ser1)

0   2009-01-01
1   2009-01-02
2   2009-01-03
3   2009-01-04
4   2009-01-05
dtype: datetime64[ns]

In [31]:
pd.to_datetime(dt_str_ser2)

0   2009-01-01
1   2009-01-02
2   2009-01-03
3   2009-01-04
4   2009-01-05
dtype: datetime64[ns]

通过上面的例子我们可以发现，常用的"%Y%m%d"或"%Y-%m-%d"格式的时间字符串会被自动识别

如果想要转换特定格式的字符串，也可以传入format参数  
比如下面的例子里，我们将月份和天数调换顺序，默认的识别方式就无法识别了

In [32]:
dt_str_list3 = ["2009-01-01", "2009-02-01", "2009-03-01", "2009-04-01", "2009-05-01", "2009-31-01"]
pd.to_datetime(dt_str_list3)

ValueError: month must be in 1..12

指定了format之后就可以识别了

In [33]:
pd.to_datetime(dt_str_list3, format="%Y-%d-%m")

DatetimeIndex(['2009-01-01', '2009-01-02', '2009-01-03', '2009-01-04',
               '2009-01-05', '2009-01-31'],
              dtype='datetime64[ns]', freq=None)

需要注意的是，无论是DatetimeIndex还是dtype为datetime64[ns]的Series，这些容器里的元素已经不是datetime.datetime对象了，而是pandas里的TimeStamp对象

In [34]:
dt_list = [datetime.datetime(2008, 1, 1), datetime.datetime(2008, 1, 2), datetime.datetime(2008, 1, 3), datetime.datetime(2008, 1, 4)]
dt_ser = pd.Series(dt_list)

In [35]:
dt_list[0]

datetime.datetime(2008, 1, 1, 0, 0)

In [36]:
type(dt_list[0])

datetime.datetime

In [37]:
dt_ser[0]

Timestamp('2008-01-01 00:00:00')

In [38]:
type(dt_ser[0])

pandas._libs.tslibs.timestamps.Timestamp

pandas.TimeStamp是pandas在datetime.datetime对象的基础上，进行了一些包装，但是datetime.datetime有的属性和方法TimeStamp都有，如year属性，strftime方法等等。

In [39]:
time_stamp = dt_ser[0]
time_stamp

Timestamp('2008-01-01 00:00:00')

In [40]:
time_stamp.year

2008

In [41]:
time_stamp.strftime("%Y%m%d")

'20080101'

大家可以理解为TimeStamp和datetime.datetime基本没有区别，大家不要对此产生困惑，pandas不用原始的datetime.datetime，而是自己又建立了一个类TimeStamp的原因可能是出于内部实现的考虑，我们不需要知道细节。

pd.to_datetime的用法很广泛，接收的参数也不一定得是list或是Series，单独的时间字符串也是可以的

In [42]:
pd.to_datetime("20080101")

Timestamp('2008-01-01 00:00:00')

### DatetimeIndex的介绍

金融时间序列数据经常需要以时间作为index，pandas里专门提供了一种元素全为时间（TimeStamp）的index，即DatetimeIndex

构建DatetimeIndex的方法主要有两种  
1.直接调用DatetimeIndex的构造函数，或者使用to_datetime函数构建

In [43]:
dt_str_list = ["2009-01-01", "2009-01-02", "2009-01-03", "2009-01-04", "2009-01-05"]

In [44]:
pd.DatetimeIndex(dt_str_list)

DatetimeIndex(['2009-01-01', '2009-01-02', '2009-01-03', '2009-01-04',
               '2009-01-05'],
              dtype='datetime64[ns]', freq=None)

In [45]:
pd.to_datetime(dt_str_list)

DatetimeIndex(['2009-01-01', '2009-01-02', '2009-01-03', '2009-01-04',
               '2009-01-05'],
              dtype='datetime64[ns]', freq=None)

2.使用pd.date_range函数生成

给定开始时间和结束时间

In [46]:
pd.date_range("2008-01-01", "2008-01-05")

DatetimeIndex(['2008-01-01', '2008-01-02', '2008-01-03', '2008-01-04',
               '2008-01-05'],
              dtype='datetime64[ns]', freq='D')

给定开始时间和需要生成的DatetimeIndex长度

In [47]:
pd.date_range("2008-01-01", periods=6)

DatetimeIndex(['2008-01-01', '2008-01-02', '2008-01-03', '2008-01-04',
               '2008-01-05', '2008-01-06'],
              dtype='datetime64[ns]', freq='D')

可以用freq参数改变频率，常见的如"m"月份，"w-mon"周一等等

In [48]:
pd.date_range("2008-01-01", "2008-12-31", freq="m")

DatetimeIndex(['2008-01-31', '2008-02-29', '2008-03-31', '2008-04-30',
               '2008-05-31', '2008-06-30', '2008-07-31', '2008-08-31',
               '2008-09-30', '2008-10-31', '2008-11-30', '2008-12-31'],
              dtype='datetime64[ns]', freq='M')

In [49]:
pd.date_range("2008-01-01", "2008-12-31", freq="w-mon")

DatetimeIndex(['2008-01-07', '2008-01-14', '2008-01-21', '2008-01-28',
               '2008-02-04', '2008-02-11', '2008-02-18', '2008-02-25',
               '2008-03-03', '2008-03-10', '2008-03-17', '2008-03-24',
               '2008-03-31', '2008-04-07', '2008-04-14', '2008-04-21',
               '2008-04-28', '2008-05-05', '2008-05-12', '2008-05-19',
               '2008-05-26', '2008-06-02', '2008-06-09', '2008-06-16',
               '2008-06-23', '2008-06-30', '2008-07-07', '2008-07-14',
               '2008-07-21', '2008-07-28', '2008-08-04', '2008-08-11',
               '2008-08-18', '2008-08-25', '2008-09-01', '2008-09-08',
               '2008-09-15', '2008-09-22', '2008-09-29', '2008-10-06',
               '2008-10-13', '2008-10-20', '2008-10-27', '2008-11-03',
               '2008-11-10', '2008-11-17', '2008-11-24', '2008-12-01',
               '2008-12-08', '2008-12-15', '2008-12-22', '2008-12-29'],
              dtype='datetime64[ns]', freq='W-MON')

In [133]:
pd.date_range("2008-01-01", "2008-12-31", freq="w-thu")

DatetimeIndex(['2008-01-03', '2008-01-10', '2008-01-17', '2008-01-24',
               '2008-01-31', '2008-02-07', '2008-02-14', '2008-02-21',
               '2008-02-28', '2008-03-06', '2008-03-13', '2008-03-20',
               '2008-03-27', '2008-04-03', '2008-04-10', '2008-04-17',
               '2008-04-24', '2008-05-01', '2008-05-08', '2008-05-15',
               '2008-05-22', '2008-05-29', '2008-06-05', '2008-06-12',
               '2008-06-19', '2008-06-26', '2008-07-03', '2008-07-10',
               '2008-07-17', '2008-07-24', '2008-07-31', '2008-08-07',
               '2008-08-14', '2008-08-21', '2008-08-28', '2008-09-04',
               '2008-09-11', '2008-09-18', '2008-09-25', '2008-10-02',
               '2008-10-09', '2008-10-16', '2008-10-23', '2008-10-30',
               '2008-11-06', '2008-11-13', '2008-11-20', '2008-11-27',
               '2008-12-04', '2008-12-11', '2008-12-18', '2008-12-25'],
              dtype='datetime64[ns]', freq='W-THU')

freq可选的取值有如下，基本满足所需，如有特殊需要需自定义，较为麻烦，有兴趣可以问我（如每年1，4，7，10月的第二个交易日星期五之类的）

![image.png](attachment:image.png)

### DatetimeIndex的索引

In [57]:
df = pd.DataFrame(np.random.randn(60, 5),
             index=pd.date_range("2010-01-01", periods=60),
             columns=["000001.SZ", "000002.SZ", "000003.SZ", "000004.SZ", "000005.SZ"])

In [71]:
df

            000001.SZ  000002.SZ  000003.SZ  000004.SZ  000005.SZ
2010-01-01   0.113398   0.425798  -0.392296   0.683009  -0.789828
2010-01-02   1.922640   0.092194   0.607691   0.172712   0.015335
2010-01-03   1.380554   0.842115   0.013588   0.347950   1.638189
2010-01-04  -0.663432   0.085455  -0.432676  -0.457802   0.611273
2010-01-05  -0.255987   0.421117   1.246094  -0.129419   0.674631
2010-01-06   0.786186  -1.615272  -0.885444  -0.657019  -0.798388
2010-01-07  -0.577109   0.298353   0.795358  -0.160196  -0.707037
2010-01-08   0.762981   0.597551  -0.046559   0.306030   0.601991
2010-01-09  -0.544763  -1.172730  -0.507936   1.528952  -0.944010
2010-01-10  -0.680500  -0.384061   1.331755   1.126256   0.404108
2010-01-11  -0.100414   0.168427  -0.098110  -0.122481  -1.123239
2010-01-12  -1.458738  -0.194948  -0.187580  -0.972029   0.123729
2010-01-13   1.660267  -1.610333  -0.235517   0.237871   0.788099
2010-01-14   0.266993  -0.355403   1.330544   0.530225  -0.960094
2010-01-15   1.345400   0.466214  -1.093540  -0.056848   0.432113
2010-01-16   0.357480   2.205909   1.129602  -0.562036   0.635201
2010-01-17   0.637413  -0.190998   0.931104   2.088947   0.163989
2010-01-18   0.019223   1.014313   0.044692   1.092538   0.777699
2010-01-19  -0.783736  -0.178383   0.316217   0.254808  -1.128514
2010-01-20  -0.770817  -0.705615  -0.383806   0.219999   0.092011
2010-01-21   0.087627   1.179755   0.061216   1.210064  -1.400359
2010-01-22  -0.468499   0.814906   0.683672   0.762707  -1.160977
2010-01-23  -0.336586   0.645704   0.703572   0.109508  -0.509416
2010-01-24  -1.858111  -0.425841   0.246660  -2.001609   1.694253
2010-01-25  -0.192936   1.197587   1.241378  -0.539374   0.331194
2010-01-26  -0.174593   0.490220   0.722631   0.967217   0.807434
2010-01-27   1.265434   0.193455  -0.131052   2.350863   0.974372
2010-01-28  -0.537306  -0.601593   0.841464   0.109184  -1.341151
2010-01-29   0.030451   0.494314   2.733505  -0.422080   1.322067
2010-01-30  -0.563251  -0.732366  -0.635901  -0.193312  -0.756863
2010-01-31   0.110974   0.291779  -0.790677  -0.378298   0.501828
2010-02-01   0.464698   0.280585  -0.922381  -0.050114   1.105453
2010-02-02  -0.486849  -0.718209  -0.889724   0.789996   0.873674
2010-02-03  -0.834263  -1.460212   0.279229   0.115128   0.951094
2010-02-04  -1.841961   0.241081  -1.147572   2.414509   0.569329
2010-02-05  -1.454713  -0.720147  -0.532582  -0.431159  -0.402441
2010-02-06   0.061453  -0.807314  -0.763929   1.254894  -1.572351
2010-02-07  -0.005774  -0.342981  -0.665846  -2.000990   0.580144
2010-02-08  -0.148830  -0.885749   0.426585   1.028307  -0.951095
2010-02-09  -0.097173  -0.599465   0.441385   0.584018   2.438998
2010-02-10  -1.265739   0.116146   0.426571  -0.702913  -0.662912
2010-02-11  -0.843426   2.193048  -1.754764  -1.778762   1.710550
2010-02-12  -0.662547  -0.566066  -0.929552   0.255761  -0.701947
2010-02-13  -0.652380  -0.658620  -0.689911   1.501580   0.554275
2010-02-14  -1.014063  -0.617597   0.317998  -0.017827  -2.351441
2010-02-15  -0.435016   0.622561  -0.167466   0.517096  -0.337792
2010-02-16  -1.119753   0.281242   0.356837  -0.985174   0.313183
2010-02-17   0.251485   0.616706   2.329744   2.165674  -1.635819
2010-02-18   0.678023   1.323680  -1.218910  -1.349512  -0.645323
2010-02-19  -1.010367  -0.984772   0.214088  -1.521241  -1.273393
2010-02-20   0.160351   0.549858   1.464130  -0.849982  -0.957769
2010-02-21  -0.437717  -0.711450   0.886030  -0.366473   0.236331
2010-02-22  -0.023885   0.127168  -0.645662  -1.362874  -0.337387
2010-02-23  -0.826603   0.261609   0.282730  -1.168335   0.461586
2010-02-24   1.253780  -0.499662  -0.919772  -1.257955   0.677143
2010-02-25   0.495050  -1.105014   0.463984  -0.662799   1.390629
2010-02-26   0.581682  -0.273854  -0.208835   0.899827  -1.152227
2010-02-27  -0.438119  -0.501204  -0.079044   1.573983  -2.054388
2010-02-28  -0.077556  -0.412275   0.210111   0.171588   1.102303
2010-03-01  -1.276263  -1.531093  -0.629115   0.379051   0.907093

带有DatetimeIndex的对象索引是比较特殊的，因为pandas为了使用上的便捷性优化了索引方法

例如，我们想要选取2010年2月28日对应的这一行

例如，虽然我们的DatetimeIndex的元素实际上是一个个TimeStamp，但我们并没有必要先构造一个TimeStamp，再将这个TimeStamp传入进行索引（当然这样做是可以的）

In [75]:
dt_str = "2010-02-28"
dt_ts = pd.to_datetime(dt_str)
dt_ts

Timestamp('2010-02-28 00:00:00')

In [78]:
df.loc[dt_ts, :]

000001.SZ   -0.077556
000002.SZ   -0.412275
000003.SZ    0.210111
000004.SZ    0.171588
000005.SZ    1.102303
Name: 2010-02-28 00:00:00, dtype: float64

事实上直接传入时间字符串就够了，在使用DatetimeIndex进行索引时，pandas会自动将我们输入的字符串转换成TimeStamp再进行索引。

In [80]:
df.loc["2010-02-28", :]

000001.SZ   -0.077556
000002.SZ   -0.412275
000003.SZ    0.210111
000004.SZ    0.171588
000005.SZ    1.102303
Name: 2010-02-28 00:00:00, dtype: float64

时间序列还提供了特殊的索引方式，如选取2010年2月的数据可以按照如下选取，当然按照年份取也是可以的

In [87]:
df.loc["2010-02", :]

            000001.SZ  000002.SZ  000003.SZ  000004.SZ  000005.SZ
2010-02-01   0.464698   0.280585  -0.922381  -0.050114   1.105453
2010-02-02  -0.486849  -0.718209  -0.889724   0.789996   0.873674
2010-02-03  -0.834263  -1.460212   0.279229   0.115128   0.951094
2010-02-04  -1.841961   0.241081  -1.147572   2.414509   0.569329
2010-02-05  -1.454713  -0.720147  -0.532582  -0.431159  -0.402441
2010-02-06   0.061453  -0.807314  -0.763929   1.254894  -1.572351
2010-02-07  -0.005774  -0.342981  -0.665846  -2.000990   0.580144
2010-02-08  -0.148830  -0.885749   0.426585   1.028307  -0.951095
2010-02-09  -0.097173  -0.599465   0.441385   0.584018   2.438998
2010-02-10  -1.265739   0.116146   0.426571  -0.702913  -0.662912
2010-02-11  -0.843426   2.193048  -1.754764  -1.778762   1.710550
2010-02-12  -0.662547  -0.566066  -0.929552   0.255761  -0.701947
2010-02-13  -0.652380  -0.658620  -0.689911   1.501580   0.554275
2010-02-14  -1.014063  -0.617597   0.317998  -0.017827  -2.351441
2010-02-15  -0.435016   0.622561  -0.167466   0.517096  -0.337792
2010-02-16  -1.119753   0.281242   0.356837  -0.985174   0.313183
2010-02-17   0.251485   0.616706   2.329744   2.165674  -1.635819
2010-02-18   0.678023   1.323680  -1.218910  -1.349512  -0.645323
2010-02-19  -1.010367  -0.984772   0.214088  -1.521241  -1.273393
2010-02-20   0.160351   0.549858   1.464130  -0.849982  -0.957769
2010-02-21  -0.437717  -0.711450   0.886030  -0.366473   0.236331
2010-02-22  -0.023885   0.127168  -0.645662  -1.362874  -0.337387
2010-02-23  -0.826603   0.261609   0.282730  -1.168335   0.461586
2010-02-24   1.253780  -0.499662  -0.919772  -1.257955   0.677143
2010-02-25   0.495050  -1.105014   0.463984  -0.662799   1.390629
2010-02-26   0.581682  -0.273854  -0.208835   0.899827  -1.152227
2010-02-27  -0.438119  -0.501204  -0.079044   1.573983  -2.054388
2010-02-28  -0.077556  -0.412275   0.210111   0.171588   1.102303

### DatetimeIndex的一些有用的属性和方法

In [96]:
dt_index = pd.date_range("2008-01-01", "2008-01-10")

In [97]:
dt_index

DatetimeIndex(['2008-01-01', '2008-01-02', '2008-01-03', '2008-01-04',
               '2008-01-05', '2008-01-06', '2008-01-07', '2008-01-08',
               '2008-01-09', '2008-01-10'],
              dtype='datetime64[ns]', freq='D')

In [98]:
dt_index.year

Int64Index([2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008], dtype='int64')

In [99]:
dt_index.month

Int64Index([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype='int64')

In [100]:
dt_index.day

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

In [101]:
dt_index.is_month_start

array([ True, False, False, False, False, False, False, False, False,
       False])

不一一列举，详细常用属性见下表：

![image.png](attachment:image.png)

![image.png](attachment:image.png)

### 用resample方法进行时间序列频率转换

我们先使用随机数生成一连串的随机收益率序列

In [117]:
# bdate_range生成的日期index和date_range最大的区别就是bdate_range不包括双休日
# 由于是模拟收益率，我们暂时没考虑交易日
return_df = pd.DataFrame(np.random.randn(700, 5),
             index=pd.bdate_range("2010-01-01", periods=700),
             columns=["000001.SZ", "000002.SZ", "000003.SZ", "000004.SZ", "000005.SZ"])/100

In [119]:
return_df

            000001.SZ  000002.SZ  000003.SZ  000004.SZ  000005.SZ
2010-01-01   0.012215  -0.009856  -0.002703  -0.011182   0.001507
2010-01-04   0.002553   0.001927  -0.012504   0.002256  -0.000010
2010-01-05   0.011596  -0.007920  -0.011301   0.008413   0.004248
2010-01-06   0.006472  -0.017252  -0.005612   0.004644  -0.018802
2010-01-07  -0.007336   0.011211   0.001757  -0.002712   0.004813
2010-01-08  -0.002699  -0.019419  -0.001394   0.013843   0.015919
2010-01-11   0.003114   0.004757  -0.018625  -0.004211   0.009386
2010-01-12  -0.011788  -0.006913   0.002988  -0.014754   0.013526
2010-01-13  -0.001721  -0.005479  -0.006050   0.007330   0.008510
2010-01-14  -0.011751   0.005454   0.006687  -0.006203   0.001241
2010-01-15  -0.004813   0.000021  -0.010045   0.001715  -0.006141
2010-01-18  -0.004621   0.009228  -0.011749  -0.005329   0.008858
2010-01-19  -0.006291   0.017364  -0.004589   0.004970  -0.020611
2010-01-20   0.010507   0.014142  -0.006467  -0.009587  -0.014796
2010-01-21   0.001947  -0.008154  -0.012197   0.001219  -0.011355
2010-01-22   0.012365  -0.003863  -0.007413   0.010336  -0.001840
2010-01-25   0.010953   0.003850  -0.004670  -0.005027   0.003890
2010-01-26   0.017087   0.031658   0.002893  -0.011814  -0.022084
2010-01-27   0.003210  -0.011107  -0.000858  -0.005825  -0.017171
2010-01-28  -0.009409  -0.013555   0.005881   0.011512  -0.005381
2010-01-29   0.000959   0.013107   0.009245   0.010224  -0.001297
2010-02-01  -0.006406   0.004426  -0.003038  -0.008051   0.007920
2010-02-02  -0.004258  -0.018430  -0.006066  -0.011983   0.005891
2010-02-03   0.003023  -0.007466  -0.010561   0.004958  -0.009658
2010-02-04  -0.004898  -0.001071  -0.006804  -0.000999   0.013255
2010-02-05   0.000139  -0.006190  -0.021566  -0.009791   0.008374
2010-02-08   0.002226   0.011575  -0.016856  -0.007639   0.000174
2010-02-09   0.001022   0.015808   0.011117   0.017082   0.005702
2010-02-10  -0.009896  -0.013541   0.010219   0.016755  -0.000329
2010-02-11  -0.006351  -0.006376   0.019920   0.019211  -0.005432
...               ...        ...        ...        ...        ...
2012-07-27   0.004799  -0.010286  -0.011945   0.011738   0.000491
2012-07-30  -0.012186   0.020608  -0.001541  -0.000007   0.006004
2012-07-31   0.007777   0.007708  -0.003549  -0.008238  -0.000198
2012-08-01   0.008044  -0.003393   0.013418  -0.028663   0.001486
2012-08-02  -0.007893   0.003817  -0.002849   0.001762  -0.019834
2012-08-03   0.019379   0.001074   0.006309   0.006523  -0.011128
2012-08-06  -0.003523  -0.000056  -0.007362   0.008577   0.013916
2012-08-07   0.008356  -0.007082   0.008746   0.021049  -0.008771
2012-08-08  -0.009063  -0.000129  -0.004983  -0.010065  -0.014759
2012-08-09   0.013476  -0.000899   0.002142  -0.009554   0.007833
2012-08-10   0.007571  -0.016572   0.017907   0.020138   0.004033
2012-08-13   0.019333  -0.014907  -0.007341   0.000322  -0.019385
2012-08-14   0.012688  -0.005724  -0.005162   0.003977   0.004485
2012-08-15   0.006124   0.009127   0.011081   0.007491  -0.004113
2012-08-16   0.001778  -0.017466   0.009263  -0.012586  -0.002021
2012-08-17   0.009792  -0.008541  -0.006721  -0.004857  -0.005677
2012-08-20   0.001438  -0.000315  -0.004282  -0.003666   0.012953
2012-08-21  -0.027727  -0.000958  -0.000339   0.013244  -0.007640
2012-08-22   0.000244  -0.008301   0.007464  -0.009790   0.013926
2012-08-23  -0.003557  -0.007331  -0.004998   0.008342   0.012657
2012-08-24  -0.001497   0.005142   0.001741  -0.004945  -0.000444
2012-08-27  -0.000432   0.010042  -0.000117   0.004232  -0.001626
2012-08-28   0.001255  -0.009222  -0.014718  -0.005821   0.002525
2012-08-29   0.005395   0.009674   0.018885  -0.011833  -0.009432
2012-08-30   0.005578  -0.008583  -0.003646  -0.000997  -0.004456
2012-08-31  -0.008200  -0.000016  -0.000692   0.001099  -0.001553
2012-09-03   0.009144  -0.009083  -0.006412   0.011565   0.011735
2012-09-04   0.020871   0.017297   0.002801   0.003644   0.005334
2012-09-05   0.015778  -0.000834   0.007980   0.002641   0.008393
2012-09-06  -0.001495   0.000266  -0.014775  -0.018495   0.006922

[700 rows x 5 columns]

用return_df可以用cumprod函数得到净值(以2010年1月1日前一个交易日的净值为1)

In [127]:
nv_df = (1 + return_df).cumprod()
nv_df

            000001.SZ  000002.SZ  000003.SZ  000004.SZ  000005.SZ
2010-01-01   1.012215   0.990144   0.997297   0.988818   1.001507
2010-01-04   1.014799   0.992051   0.984826   0.991049   1.001497
2010-01-05   1.026567   0.984194   0.973696   0.999387   1.005751
2010-01-06   1.033211   0.967215   0.968232   1.004028   0.986841
2010-01-07   1.025631   0.978058   0.969933   1.001305   0.991591
2010-01-08   1.022862   0.959065   0.968581   1.015166   1.007376
2010-01-11   1.026048   0.963628   0.950542   1.010891   1.016831
2010-01-12   1.013953   0.956966   0.953381   0.995976   1.030585
2010-01-13   1.012208   0.951722   0.947613   1.003277   1.039355
2010-01-14   1.000314   0.956913   0.953950   0.997054   1.040645
2010-01-15   0.995499   0.956933   0.944368   0.998763   1.034254
2010-01-18   0.990899   0.965764   0.933272   0.993441   1.043416
2010-01-19   0.984665   0.982533   0.928990   0.998379   1.021910
2010-01-20   0.995011   0.996429   0.922982   0.988807   1.006791
2010-01-21   0.996948   0.988304   0.911724   0.990013   0.995359
2010-01-22   1.009275   0.984486   0.904965   1.000246   0.993528
2010-01-25   1.020329   0.988277   0.900739   0.995218   0.997392
2010-01-26   1.037764   1.019563   0.903345   0.983460   0.975366
2010-01-27   1.041095   1.008239   0.902570   0.977732   0.958617
2010-01-28   1.031300   0.994572   0.907878   0.988988   0.953459
2010-01-29   1.032289   1.007609   0.916272   0.999099   0.952223
2010-02-01   1.025676   1.012068   0.913489   0.991055   0.959765
2010-02-02   1.021309   0.993416   0.907947   0.979179   0.965418
2010-02-03   1.024397   0.985999   0.898358   0.984035   0.956095
2010-02-04   1.019379   0.984943   0.892246   0.983051   0.968767
2010-02-05   1.019521   0.978847   0.873003   0.973427   0.976880
2010-02-08   1.021790   0.990177   0.858288   0.965991   0.977050
2010-02-09   1.022834   1.005829   0.867830   0.982493   0.982621
2010-02-10   1.012712   0.992210   0.876698   0.998954   0.982299
2010-02-11   1.006281   0.985884   0.894162   1.018145   0.976963
...               ...        ...        ...        ...        ...
2012-07-27   0.773218   0.786532   1.208622   0.517462   1.014105
2012-07-30   0.763796   0.802741   1.206760   0.517458   1.020194
2012-07-31   0.769736   0.808929   1.202478   0.513195   1.019992
2012-08-01   0.775928   0.806184   1.218613   0.498485   1.021507
2012-08-02   0.769803   0.809262   1.215140   0.499364   1.001246
2012-08-03   0.784721   0.810130   1.222806   0.502621   0.990104
2012-08-06   0.781956   0.810085   1.213804   0.506932   1.003883
2012-08-07   0.788491   0.804348   1.224421   0.517602   0.995078
2012-08-08   0.781345   0.804244   1.218320   0.512393   0.980392
2012-08-09   0.791874   0.803522   1.220929   0.507497   0.988072
2012-08-10   0.797869   0.790206   1.242793   0.517717   0.992058
2012-08-13   0.813295   0.778427   1.233669   0.517884   0.972826
2012-08-14   0.823614   0.773971   1.227301   0.519944   0.977189
2012-08-15   0.828658   0.781035   1.240900   0.523839   0.973169
2012-08-16   0.830131   0.767393   1.252395   0.517246   0.971202
2012-08-17   0.838260   0.760839   1.243978   0.514733   0.965689
2012-08-20   0.839465   0.760600   1.238652   0.512846   0.978197
2012-08-21   0.816189   0.759871   1.238232   0.519638   0.970724
2012-08-22   0.816388   0.753563   1.247473   0.514551   0.984242
2012-08-23   0.813484   0.748039   1.241238   0.518843   0.996700
2012-08-24   0.812266   0.751885   1.243399   0.516277   0.996257
2012-08-27   0.811915   0.759435   1.243254   0.518462   0.994637
2012-08-28   0.812934   0.752432   1.224956   0.515444   0.997149
2012-08-29   0.817320   0.759710   1.248089   0.509345   0.987744
2012-08-30   0.821879   0.753190   1.243539   0.508837   0.983343
2012-08-31   0.815139   0.753177   1.242679   0.509396   0.981816
2012-09-03   0.822593   0.746336   1.234712   0.515288   0.993338
2012-09-04   0.839762   0.759245   1.238170   0.517165   0.998637
2012-09-05   0.853011   0.758612   1.248051   0.518531   1.007018
2012-09-06   0.851736   0.758813   1.229611   0.508941   1.013989

[700 rows x 5 columns]

将净值数据由日频转换为月频，我们通常需要以每个月最后一天净值作为该月净值就可以了

In [132]:
nv_df.resample("m").last()

            000001.SZ  000002.SZ  000003.SZ  000004.SZ  000005.SZ
2010-01-31   1.032289   1.007609   0.916272   0.999099   0.952223
2010-02-28   1.012660   0.976189   0.909228   0.980903   0.975435
2010-03-31   1.020488   0.953678   0.939190   0.967840   1.018407
2010-04-30   1.044703   0.908587   0.966065   0.943724   1.012950
2010-05-31   1.059225   0.936579   1.010587   0.899905   0.974140
2010-06-30   1.112189   0.974954   1.028977   0.924888   0.943945
2010-07-31   1.123791   0.931041   0.924324   0.926070   0.902659
2010-08-31   1.144221   0.925494   0.850200   0.888783   0.962361
2010-09-30   1.169096   0.927286   0.903728   0.818848   0.921932
2010-10-31   1.099271   0.974880   0.906626   0.903546   0.912034
2010-11-30   1.013714   1.002199   0.861484   0.893251   0.917610
2010-12-31   1.119274   0.995711   0.912217   0.891297   0.948027
2011-01-31   1.133110   0.993776   0.952733   0.921057   0.913528
2011-02-28   1.218260   0.877353   0.948571   0.913122   0.960661
2011-03-31   1.186704   0.861987   0.916084   0.911099   1.001454
2011-04-30   1.195917   0.845559   0.949617   0.817624   0.940375
2011-05-31   1.168987   0.804337   0.992563   0.829722   0.969036
2011-06-30   1.129145   0.721764   1.036106   0.862901   0.976852
2011-07-31   1.116619   0.744130   1.024467   0.812243   1.003746
2011-08-31   1.110782   0.750071   0.976070   0.808206   1.069086
2011-09-30   1.122739   0.745526   1.001192   0.713070   1.200607
2011-10-31   1.116296   0.765364   0.986169   0.671391   1.128889
2011-11-30   1.053054   0.786665   1.024873   0.677370   1.053276
2011-12-31   1.001078   0.764255   1.017146   0.662864   1.154564
2012-01-31   0.952249   0.791720   1.038990   0.652611   1.167150
2012-02-29   0.979717   0.851436   1.106450   0.625836   1.333281
2012-03-31   0.892386   0.884310   1.092010   0.574741   1.256722
2012-04-30   0.832008   0.863903   1.117260   0.568734   1.259187
2012-05-31   0.782724   0.799370   1.081043   0.546917   1.169245
2012-06-30   0.731038   0.809945   1.109230   0.538992   1.069677
2012-07-31   0.769736   0.808929   1.202478   0.513195   1.019992
2012-08-31   0.815139   0.753177   1.242679   0.509396   0.981816
2012-09-30   0.851736   0.758813   1.229611   0.508941   1.013989

将收益率由日频转换为月频，我们通常需要计算每个月的收益率和，即 (1+r1)(1+r2)(1+r3)...(1+r31)-1

In [137]:
(1+return_df).resample("m").prod()-1

            000001.SZ  000002.SZ  000003.SZ  000004.SZ  000005.SZ
2010-01-31   0.032289   0.007609  -0.083728  -0.000901  -0.047777
2010-02-28  -0.019015  -0.031182  -0.007687  -0.018212   0.024377
2010-03-31   0.007730  -0.023061   0.032953  -0.013317   0.044054
2010-04-30   0.023728  -0.047280   0.028615  -0.024918  -0.005358
2010-05-31   0.013901   0.030807   0.046086  -0.046432  -0.038314
2010-06-30   0.050002   0.040974   0.018197   0.027761  -0.030996
2010-07-31   0.010432  -0.045041  -0.101705   0.001279  -0.043738
2010-08-31   0.018180  -0.005959  -0.080193  -0.040265   0.066141
2010-09-30   0.021740   0.001937   0.062959  -0.078686  -0.042011
2010-10-31  -0.059726   0.051326   0.003208   0.103436  -0.010735
2010-11-30  -0.077830   0.028023  -0.049791  -0.011394   0.006113
2010-12-31   0.104131  -0.006474   0.058889  -0.002188   0.033148
2011-01-31   0.012362  -0.001943   0.044415   0.033389  -0.036390
2011-02-28   0.075147  -0.117152  -0.004369  -0.008615   0.051594
2011-03-31  -0.025903  -0.017514  -0.034248  -0.002216   0.042463
2011-04-30   0.007763  -0.019058   0.036605  -0.102596  -0.060990
2011-05-31  -0.022518  -0.048752   0.045225   0.014796   0.030478
2011-06-30  -0.034083  -0.102660   0.043869   0.039989   0.008066
2011-07-31  -0.011093   0.030988  -0.011233  -0.058707   0.027531
2011-08-31  -0.005228   0.007984  -0.047241  -0.004970   0.065096
2011-09-30   0.010765  -0.006059   0.025737  -0.117712   0.123022
2011-10-31  -0.005738   0.026609  -0.015005  -0.058450  -0.059735
2011-11-30  -0.056654   0.027832   0.039247   0.008905  -0.066979
2011-12-31  -0.049357  -0.028488  -0.007539  -0.021415   0.096164
2012-01-31  -0.048776   0.035937   0.021475  -0.015468   0.010901
2012-02-29   0.028845   0.075426   0.064928  -0.041027   0.142339
2012-03-31  -0.089139   0.038610  -0.013050  -0.081642  -0.057421
2012-04-30  -0.067660  -0.023077   0.023122  -0.010453   0.001961
2012-05-31  -0.059234  -0.074700  -0.032416  -0.038359  -0.071429
2012-06-30  -0.066033   0.013229   0.026074  -0.014491  -0.085156
2012-07-31   0.052935  -0.001254   0.084065  -0.047861  -0.046449
2012-08-31   0.058986  -0.068920   0.033432  -0.007403  -0.037427
2012-09-30   0.044896   0.007483  -0.010516  -0.000894   0.032769

大家会发现这个和groupby的用法很像，除了我们刚刚用的last和sum，实际上还有其他很多可选方法

![image.png](attachment:image.png)

当然，他也可以接收apply方法，用于接收自定义函数

依旧使用我们常用的小技巧，在传入apply的函数里，加上print(),观看resample究竟传入了什么

In [141]:
def myfun(x):
    print(type(x), )
    print(x, "\n\n")
    return 1
nv_df.resample("m").apply(myfun)

<class 'pandas.core.series.Series'>
2010-01-01    1.012215
2010-01-04    1.014799
2010-01-05    1.026567
2010-01-06    1.033211
2010-01-07    1.025631
2010-01-08    1.022862
2010-01-11    1.026048
2010-01-12    1.013953
2010-01-13    1.012208
2010-01-14    1.000314
2010-01-15    0.995499
2010-01-18    0.990899
2010-01-19    0.984665
2010-01-20    0.995011
2010-01-21    0.996948
2010-01-22    1.009275
2010-01-25    1.020329
2010-01-26    1.037764
2010-01-27    1.041095
2010-01-28    1.031300
2010-01-29    1.032289
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2010-02-01    1.025676
2010-02-02    1.021309
2010-02-03    1.024397
2010-02-04    1.019379
2010-02-05    1.019521
2010-02-08    1.021790
2010-02-09    1.022834
2010-02-10    1.012712
2010-02-11    1.006281
2010-02-12    1.021895
2010-02-15    1.012276
2010-02-16    1.029414
2010-02-17    1.010988
2010-02-18    0.998827
2010-02-19    1.006362
2010-02-22    1.014059
2010-02-23    1.012835
2010-02-24    1.015283
2010-02-25    1.004836
2010-02-26    1.012660
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2010-03-01    1.003843
2010-03-02    0.989826
2010-03-03    0.972514
2010-03-04    0.970020
2010-03-05    0.967541
2010-03-08    0.963901
2010-03-09    0.958271
2010-03-10    0.968945
2010-03-11    0.980382
2010-03-12    0.980399
2010-03-15    0.979247
2010-03-16    0.978828
2010-03-17    0.998780
2010-03-18    1.006299
2010-03-19    1.025910
2010-03-22    1.043473
2010-03-23    1.035699
2010-03-24    1.033245
2010-03-25    1.038211
2010-03-26    1.033652
2010-03-29    1.035490
2010-03-30    1.025459
2010-03-31    1.020488
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2010-04-01    1.022605
2010-04-02    1.019574
2010-04-05    1.015721
2010-04-06    1.019367
2010-04-07    1.025399
2010-04-08    1.025478
2010-04-09    1.022022
2010-04-12    1.017763
2010-04-13    1.017050
2010-04-14    1.031031
2010-04-15    1.033994
2010-04-16    1.015066
2010-04-19    1.003157
2010-04-20    0.990563
2010-04-21    0.997462
2010-04-22    0.991414
2010-04-23    0.997926
2010-04-26    0.998994
2010-04-27    1.005107
2010-04-28    1.021721
2010-04-29    1.034249
2010-04-30    1.044703
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2010-05-03    1.042882
2010-05-04    1.032035
2010-05-05    1.041742
2010-05-06    1.061888
2010-05-07    1.067082
2010-05-10    1.069816
2010-05-11    1.081486
2010-05-12    1.083250
2010-05-13    1.076112
2010-05-14    1.080454
2010-05-17    1.093435
2010-05-18    1.092083
2010-05-19    1.074953
2010-05-20    1.056910
2010-05-21    1.054122
2010-05-24    1.027996
2010-05-25    1.030855
2010-05-26    1.033490
2010-05-27    1.062427
2010-05-28    1.058433
2010-05-31    1.059225
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2010-06-01    1.067200
2010-06-02    1.058351
2010-06-03    1.054373
2010-06-04    1.070014
2010-06-07    1.086304
2010-06-08    1.075862
2010-06-09    1.083887
2010-06-10    1.080298
2010-06-11    1.057539
2010-06-14    1.069102
2010-06-15    1.071012
2010-06-16    1.073005
2010-06-17    1.097501
2010-06-18    1.107913
2010-06-21    1.107925
2010-06-22    1.098857
2010-06-23    1.107961
2010-06-24    1.103431
2010-06-25    1.126128
2010-06-28    1.111086
2010-06-29    1.115594
2010-06-30    1.112189
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2010-07-01    1.123336
2010-07-02    1.124412
2010-07-05    1.120821
2010-07-06    1.121598
2010-07-07    1.128251
2010-07-08    1.111365
2010-07-09    1.105989
2010-07-12    1.104784
2010-07-13    1.102028
2010-07-14    1.107639
2010-07-15    1.114488
2010-07-16    1.115276
2010-07-19    1.118041
2010-07-20    1.133329
2010-07-21    1.122953
2010-07-22    1.126013
2010-07-23    1.114178
2010-07-26    1.102736
2010-07-27    1.100565
2010-07-28    1.099118
2010-07-29    1.111584
2010-07-30    1.123791
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2010-08-02    1.124024
2010-08-03    1.126337
2010-08-04    1.124964
2010-08-05    1.129134
2010-08-06    1.120400
2010-08-09    1.139087
2010-08-10    1.128794
2010-08-11    1.117867
2010-08-12    1.115499
2010-08-13    1.124846
2010-08-16    1.130942
2010-08-17    1.114607
2010-08-18    1.114107
2010-08-19    1.124809
2010-08-20    1.144181
2010-08-23    1.140407
2010-08-24    1.145765
2010-08-25    1.162079
2010-08-26    1.141647
2010-08-27    1.127543
2010-08-30    1.126607
2010-08-31    1.144221
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2010-09-01    1.138285
2010-09-02    1.141736
2010-09-03    1.152541
2010-09-06    1.146649
2010-09-07    1.147584
2010-09-08    1.123997
2010-09-09    1.129917
2010-09-10    1.137204
2010-09-13    1.157231
2010-09-14    1.127129
2010-09-15    1.123515
2010-09-16    1.131410
2010-09-17    1.126027
2010-09-20    1.140856
2010-09-21    1.136050
2010-09-22    1.156520
2010-09-23    1.175107
2010-09-24    1.178948
2010-09-27    1.189246
2010-09-28    1.173157
2010-09-29    1.168789
2010-09-30    1.169096
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2010-10-01    1.160526
2010-10-04    1.141087
2010-10-05    1.143485
2010-10-06    1.147345
2010-10-07    1.147517
2010-10-08    1.121161
2010-10-11    1.123944
2010-10-12    1.095100
2010-10-13    1.112518
2010-10-14    1.132137
2010-10-15    1.139202
2010-10-18    1.140976
2010-10-19    1.130416
2010-10-20    1.118417
2010-10-21    1.115999
2010-10-22    1.104447
2010-10-25    1.099516
2010-10-26    1.083394
2010-10-27    1.089003
2010-10-28    1.088083
2010-10-29    1.099271
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2010-11-01    1.090031
2010-11-02    1.092932
2010-11-03    1.099732
2010-11-04    1.086953
2010-11-05    1.091836
2010-11-08    1.082081
2010-11-09    1.072572
2010-11-10    1.068582
2010-11-11    1.058291
2010-11-12    1.056417
2010-11-15    1.046772
2010-11-16    1.057402
2010-11-17    1.053234
2010-11-18    1.052104
2010-11-19    1.048098
2010-11-22    1.039770
2010-11-23    1.048532
2010-11-24    1.051084
2010-11-25    1.036168
2010-11-26    1.032723
2010-11-29    1.018817
2010-11-30    1.013714
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2010-12-01    1.019444
2010-12-02    1.003263
2010-12-03    1.002861
2010-12-06    1.012266
2010-12-07    1.022549
2010-12-08    1.025482
2010-12-09    1.030851
2010-12-10    1.046641
2010-12-13    1.038098
2010-12-14    1.054732
2010-12-15    1.034884
2010-12-16    1.058715
2010-12-17    1.064905
2010-12-20    1.057733
2010-12-21    1.062559
2010-12-22    1.075538
2010-12-23    1.073716
2010-12-24    1.065802
2010-12-27    1.059983
2010-12-28    1.081658
2010-12-29    1.091257
2010-12-30    1.095696
2010-12-31    1.119274
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2011-01-03    1.114268
2011-01-04    1.135039
2011-01-05    1.127510
2011-01-06    1.126018
2011-01-07    1.110495
2011-01-10    1.116183
2011-01-11    1.122126
2011-01-12    1.107954
2011-01-13    1.104095
2011-01-14    1.095656
2011-01-17    1.084254
2011-01-18    1.082155
2011-01-19    1.095598
2011-01-20    1.110287
2011-01-21    1.120596
2011-01-24    1.144251
2011-01-25    1.160528
2011-01-26    1.167110
2011-01-27    1.161256
2011-01-28    1.150996
2011-01-31    1.133110
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2011-02-01    1.139249
2011-02-02    1.143356
2011-02-03    1.123916
2011-02-04    1.127983
2011-02-07    1.135949
2011-02-08    1.112714
2011-02-09    1.144140
2011-02-10    1.145946
2011-02-11    1.153299
2011-02-14    1.153901
2011-02-15    1.149836
2011-02-16    1.154506
2011-02-17    1.167623
2011-02-18    1.175348
2011-02-21    1.167145
2011-02-22    1.181808
2011-02-23    1.204335
2011-02-24    1.209368
2011-02-25    1.210869
2011-02-28    1.218260
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2011-03-01    1.211551
2011-03-02    1.216840
2011-03-03    1.209297
2011-03-04    1.200647
2011-03-07    1.189520
2011-03-08    1.198641
2011-03-09    1.190098
2011-03-10    1.194147
2011-03-11    1.183959
2011-03-14    1.190798
2011-03-15    1.189439
2011-03-16    1.198787
2011-03-17    1.189490
2011-03-18    1.217554
2011-03-21    1.218115
2011-03-22    1.211854
2011-03-23    1.225384
2011-03-24    1.219231
2011-03-25    1.205583
2011-03-28    1.200979
2011-03-29    1.202693
2011-03-30    1.182328
2011-03-31    1.186704
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2011-04-01    1.174178
2011-04-04    1.185865
2011-04-05    1.189066
2011-04-06    1.208826
2011-04-07    1.203261
2011-04-08    1.184559
2011-04-11    1.190203
2011-04-12    1.192719
2011-04-13    1.180072
2011-04-14    1.181733
2011-04-15    1.211908
2011-04-18    1.199326
2011-04-19    1.201826
2011-04-20    1.204496
2011-04-21    1.210333
2011-04-22    1.201957
2011-04-25    1.210935
2011-04-26    1.198050
2011-04-27    1.209112
2011-04-28    1.218400
2011-04-29    1.195917
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2011-05-02    1.204843
2011-05-03    1.212286
2011-05-04    1.210256
2011-05-05    1.222148
2011-05-06    1.204138
2011-05-09    1.195581
2011-05-10    1.197871
2011-05-11    1.186779
2011-05-12    1.194373
2011-05-13    1.193106
2011-05-16    1.189644
2011-05-17    1.181470
2011-05-18    1.190189
2011-05-19    1.180343
2011-05-20    1.187135
2011-05-23    1.178190
2011-05-24    1.201362
2011-05-25    1.192005
2011-05-26    1.177063
2011-05-27    1.191688
2011-05-30    1.185938
2011-05-31    1.168987
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2011-06-01    1.166121
2011-06-02    1.150460
2011-06-03    1.165949
2011-06-06    1.171628
2011-06-07    1.150984
2011-06-08    1.150110
2011-06-09    1.159810
2011-06-10    1.150317
2011-06-13    1.161131
2011-06-14    1.174988
2011-06-15    1.187098
2011-06-16    1.177446
2011-06-17    1.177750
2011-06-20    1.171601
2011-06-21    1.155122
2011-06-22    1.139999
2011-06-23    1.125304
2011-06-24    1.128420
2011-06-27    1.128665
2011-06-28    1.128081
2011-06-29    1.132040
2011-06-30    1.129145
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2011-07-01    1.135337
2011-07-04    1.149417
2011-07-05    1.163534
2011-07-06    1.164883
2011-07-07    1.154185
2011-07-08    1.170404
2011-07-11    1.162809
2011-07-12    1.149151
2011-07-13    1.157710
2011-07-14    1.156191
2011-07-15    1.148104
2011-07-18    1.137528
2011-07-19    1.142863
2011-07-20    1.135660
2011-07-21    1.117686
2011-07-22    1.121997
2011-07-25    1.114339
2011-07-26    1.109872
2011-07-27    1.110680
2011-07-28    1.116309
2011-07-29    1.116619
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2011-08-01    1.137398
2011-08-02    1.146780
2011-08-03    1.138898
2011-08-04    1.136984
2011-08-05    1.128088
2011-08-08    1.143858
2011-08-09    1.155379
2011-08-10    1.166868
2011-08-11    1.174097
2011-08-12    1.180791
2011-08-15    1.199605
2011-08-16    1.201201
2011-08-17    1.207646
2011-08-18    1.210906
2011-08-19    1.203423
2011-08-22    1.192725
2011-08-23    1.199874
2011-08-24    1.176521
2011-08-25    1.165823
2011-08-26    1.130397
2011-08-29    1.136238
2011-08-30    1.125385
2011-08-31    1.110782
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2011-09-01    1.100935
2011-09-02    1.096357
2011-09-05    1.109531
2011-09-06    1.090469
2011-09-07    1.112729
2011-09-08    1.099068
2011-09-09    1.109662
2011-09-12    1.103743
2011-09-13    1.101445
2011-09-14    1.091404
2011-09-15    1.078825
2011-09-16    1.080723
2011-09-19    1.080041
2011-09-20    1.072663
2011-09-21    1.072440
2011-09-22    1.075344
2011-09-23    1.071413
2011-09-26    1.083961
2011-09-27    1.089373
2011-09-28    1.100318
2011-09-29    1.114606
2011-09-30    1.122739
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2011-10-03    1.119404
2011-10-04    1.128240
2011-10-05    1.118528
2011-10-06    1.112233
2011-10-07    1.116734
2011-10-10    1.126105
2011-10-11    1.132227
2011-10-12    1.124076
2011-10-13    1.107069
2011-10-14    1.112829
2011-10-17    1.126678
2011-10-18    1.127448
2011-10-19    1.133368
2011-10-20    1.131787
2011-10-21    1.146814
2011-10-24    1.136790
2011-10-25    1.128799
2011-10-26    1.129939
2011-10-27    1.129025
2011-10-28    1.120156
2011-10-31    1.116296
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2011-11-01    1.118083
2011-11-02    1.110780
2011-11-03    1.103477
2011-11-04    1.112997
2011-11-07    1.102805
2011-11-08    1.085240
2011-11-09    1.088665
2011-11-10    1.073126
2011-11-11    1.067697
2011-11-14    1.063964
2011-11-15    1.065310
2011-11-16    1.063839
2011-11-17    1.051888
2011-11-18    1.066752
2011-11-21    1.075092
2011-11-22    1.081116
2011-11-23    1.067825
2011-11-24    1.059485
2011-11-25    1.063268
2011-11-28    1.067010
2011-11-29    1.065267
2011-11-30    1.053054
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2011-12-01    1.058580
2011-12-02    1.059345
2011-12-05    1.059724
2011-12-06    1.061947
2011-12-07    1.075206
2011-12-08    1.068643
2011-12-09    1.059107
2011-12-12    1.046032
2011-12-13    1.049389
2011-12-14    1.052143
2011-12-15    1.043180
2011-12-16    1.051532
2011-12-19    1.057997
2011-12-20    1.053194
2011-12-21    1.052099
2011-12-22    1.052498
2011-12-23    1.043202
2011-12-26    1.050188
2011-12-27    1.040987
2011-12-28    1.022233
2011-12-29    1.006268
2011-12-30    1.001078
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2012-01-02    1.001745
2012-01-03    0.994490
2012-01-04    0.990641
2012-01-05    0.977389
2012-01-06    0.983642
2012-01-09    0.987322
2012-01-10    0.992581
2012-01-11    0.970459
2012-01-12    0.968893
2012-01-13    0.952679
2012-01-16    0.949021
2012-01-17    0.944114
2012-01-18    0.948520
2012-01-19    0.944965
2012-01-20    0.940762
2012-01-23    0.935199
2012-01-24    0.938458
2012-01-25    0.933433
2012-01-26    0.958501
2012-01-27    0.955326
2012-01-30    0.954529
2012-01-31    0.952249
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2012-02-01    0.950413
2012-02-02    0.948918
2012-02-03    0.952818
2012-02-06    0.962427
2012-02-07    0.967707
2012-02-08    0.969606
2012-02-09    0.973921
2012-02-10    0.973403
2012-02-13    0.965602
2012-02-14    0.959428
2012-02-15    0.952525
2012-02-16    0.945199
2012-02-17    0.953788
2012-02-20    0.962073
2012-02-21    0.959668
2012-02-22    0.981931
2012-02-23    0.971752
2012-02-24    0.995117
2012-02-27    0.976897
2012-02-28    0.978903
2012-02-29    0.979717
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2012-03-01    0.997102
2012-03-02    1.003156
2012-03-05    0.995019
2012-03-06    0.989925
2012-03-07    0.980799
2012-03-08    0.965664
2012-03-09    0.940447
2012-03-12    0.931795
2012-03-13    0.926867
2012-03-14    0.923738
2012-03-15    0.923157
2012-03-16    0.918833
2012-03-19    0.910712
2012-03-20    0.896055
2012-03-21    0.902731
2012-03-22    0.903145
2012-03-23    0.891742
2012-03-26    0.895100
2012-03-27    0.896480
2012-03-28    0.895014
2012-03-29    0.895313
2012-03-30    0.892386
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2012-04-02    0.889658
2012-04-03    0.877035
2012-04-04    0.871238
2012-04-05    0.881124
2012-04-06    0.871381
2012-04-09    0.868358
2012-04-10    0.859757
2012-04-11    0.859162
2012-04-12    0.863621
2012-04-13    0.852904
2012-04-16    0.859571
2012-04-17    0.870342
2012-04-18    0.859756
2012-04-19    0.859652
2012-04-20    0.857544
2012-04-23    0.853106
2012-04-24    0.847653
2012-04-25    0.852918
2012-04-26    0.845472
2012-04-27    0.831429
2012-04-30    0.832008
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2012-05-01    0.835916
2012-05-02    0.836195
2012-05-03    0.834118
2012-05-04    0.817710
2012-05-07    0.820041
2012-05-08    0.825715
2012-05-09    0.824599
2012-05-10    0.815119
2012-05-11    0.813696
2012-05-14    0.815155
2012-05-15    0.802008
2012-05-16    0.803549
2012-05-17    0.800281
2012-05-18    0.805065
2012-05-21    0.808734
2012-05-22    0.810500
2012-05-23    0.811662
2012-05-24    0.796250
2012-05-25    0.808609
2012-05-28    0.806094
2012-05-29    0.793219
2012-05-30    0.787300
2012-05-31    0.782724
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2012-06-01    0.766486
2012-06-04    0.760331
2012-06-05    0.756819
2012-06-06    0.753287
2012-06-07    0.743961
2012-06-08    0.752562
2012-06-11    0.746050
2012-06-12    0.767527
2012-06-13    0.772665
2012-06-14    0.763285
2012-06-15    0.764406
2012-06-18    0.763687
2012-06-19    0.761500
2012-06-20    0.755345
2012-06-21    0.743744
2012-06-22    0.741364
2012-06-25    0.753161
2012-06-26    0.757472
2012-06-27    0.738198
2012-06-28    0.731366
2012-06-29    0.731038
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2012-07-02    0.742226
2012-07-03    0.748027
2012-07-04    0.747030
2012-07-05    0.753287
2012-07-06    0.754764
2012-07-09    0.760135
2012-07-10    0.769234
2012-07-11    0.773476
2012-07-12    0.760191
2012-07-13    0.754507
2012-07-16    0.747414
2012-07-17    0.753820
2012-07-18    0.759461
2012-07-19    0.767518
2012-07-20    0.779940
2012-07-23    0.772658
2012-07-24    0.782541
2012-07-25    0.774988
2012-07-26    0.769525
2012-07-27    0.773218
2012-07-30    0.763796
2012-07-31    0.769736
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2012-08-01    0.775928
2012-08-02    0.769803
2012-08-03    0.784721
2012-08-06    0.781956
2012-08-07    0.788491
2012-08-08    0.781345
2012-08-09    0.791874
2012-08-10    0.797869
2012-08-13    0.813295
2012-08-14    0.823614
2012-08-15    0.828658
2012-08-16    0.830131
2012-08-17    0.838260
2012-08-20    0.839465
2012-08-21    0.816189
2012-08-22    0.816388
2012-08-23    0.813484
2012-08-24    0.812266
2012-08-27    0.811915
2012-08-28    0.812934
2012-08-29    0.817320
2012-08-30    0.821879
2012-08-31    0.815139
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2012-09-03    0.822593
2012-09-04    0.839762
2012-09-05    0.853011
2012-09-06    0.851736
Name: 000001.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2010-01-01    0.990144
2010-01-04    0.992051
2010-01-05    0.984194
2010-01-06    0.967215
2010-01-07    0.978058
2010-01-08    0.959065
2010-01-11    0.963628
2010-01-12    0.956966
2010-01-13    0.951722
2010-01-14    0.956913
2010-01-15    0.956933
2010-01-18    0.965764
2010-01-19    0.982533
2010-01-20    0.996429
2010-01-21    0.988304
2010-01-22    0.984486
2010-01-25    0.988277
2010-01-26    1.019563
2010-01-27    1.008239
2010-01-28    0.994572
2010-01-29    1.007609
Name: 000002.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2010-02-01    1.012068
2010-02-02    0.993416
2010-02-03    0.985999
2010-02-04    0.984943
2010-02-05    0.978847
2010-02-08    0.990177
2010-02-09    1.005829
2010-02-10    0.992210
2010-02-11    0.985884
2010-02-12    0.986318
2010-02-15    0.978006
2010-02-16    0.961955
2010-02-17    0.961269
2010-02-18    0.951373
2010-02-19    0.943453
2010-02-22    0.949348
2010-02-23    0.963092
2010-02-24    0.968568
2010-02-25    0.970520
2010-02-26    0.976189
Name: 000002.SZ, dtype: float64


<class 'pandas.core.series.Series'>
2010-03-01    0.984373
2010-03-02    1.002534
2010-03-03    0.999045
2010-03-04    0.979898
2010-03-05    0.973650
2010-03-08    0.977413
2010-03-09    0.971112
2010-03-10    0.967170
2010-03-11    0.962581
2010-03-12    0.955285
2010-03-15    0.949165
2010-03-16    0.962114
2010-03-17    0.967253
2010-03-18    0.959142
2010-03-19    0.958811
2010-03-22    0.968423
2010-03-23    0.957429
2010-03-24    0.962401
2010-03-25    0.966385
2010-03-26    0.968552

            000001.SZ  000002.SZ  000003.SZ  000004.SZ  000005.SZ
2010-01-31        1.0        1.0        1.0        1.0        1.0
2010-02-28        1.0        1.0        1.0        1.0        1.0
2010-03-31        1.0        1.0        1.0        1.0        1.0
2010-04-30        1.0        1.0        1.0        1.0        1.0
2010-05-31        1.0        1.0        1.0        1.0        1.0
2010-06-30        1.0        1.0        1.0        1.0        1.0
2010-07-31        1.0        1.0        1.0        1.0        1.0
2010-08-31        1.0        1.0        1.0        1.0        1.0
2010-09-30        1.0        1.0        1.0        1.0        1.0
2010-10-31        1.0        1.0        1.0        1.0        1.0
2010-11-30        1.0        1.0        1.0        1.0        1.0
2010-12-31        1.0        1.0        1.0        1.0        1.0
2011-01-31        1.0        1.0        1.0        1.0        1.0
2011-02-28        1.0        1.0        1.0        1.0        1.0
2011-03-31        1.0        1.0        1.0        1.0        1.0
2011-04-30        1.0        1.0        1.0        1.0        1.0
2011-05-31        1.0        1.0        1.0        1.0        1.0
2011-06-30        1.0        1.0        1.0        1.0        1.0
2011-07-31        1.0        1.0        1.0        1.0        1.0
2011-08-31        1.0        1.0        1.0        1.0        1.0
2011-09-30        1.0        1.0        1.0        1.0        1.0
2011-10-31        1.0        1.0        1.0        1.0        1.0
2011-11-30        1.0        1.0        1.0        1.0        1.0
2011-12-31        1.0        1.0        1.0        1.0        1.0
2012-01-31        1.0        1.0        1.0        1.0        1.0
2012-02-29        1.0        1.0        1.0        1.0        1.0
2012-03-31        1.0        1.0        1.0        1.0        1.0
2012-04-30        1.0        1.0        1.0        1.0        1.0
2012-05-31        1.0        1.0        1.0        1.0        1.0
2012-06-30        1.0        1.0        1.0        1.0        1.0
2012-07-31        1.0        1.0        1.0        1.0        1.0
2012-08-31        1.0        1.0        1.0        1.0        1.0
2012-09-30        1.0        1.0        1.0        1.0        1.0